Repository urbanairship/urbanairship-cordova, pull requests merged in 2018-06, with the labels that each got.

#231 [MOBILE-200] title and subtitle, aps push event fields
  src/android/UAirshipPlugin.java
  src/ios/UAirshipPlugin.m
  www/UrbanAirship.js
Labels: needs-review

#229 [MOBILE-177] android SDK 9.3, FCM support
  README.md
  config_sample.xml
  src/android/build-extras.gradle
Labels: needs-review

#228 [MOBILE-193] support for loading custom notification categories
  README.md
  src/android/CordovaAutopilot.java
  src/ios/UAirshipPlugin.m
Labels: reviewed

#235 [MOBILE-215] Enable takeOff from JS for Android
  package.json
  plugin.xml
  src/android/ConfigUtils.java
  src/android/CordovaAirshipReceiver.java
  src/android/CordovaAutopilot.java
  src/android/CordovaNotificationFactory.java
  src/android/CustomLandingPageActivity.java
  src/android/CustomMessageActivity.java
  src/android/CustomMessageCenterActivity.java
  src/android/PluginManager.java
  src/android/UAirshipPlugin.java
  src/android/UAirshipPluginManager.java
  src/android/events/DeepLinkEvent.java
  src/android/events/Event.java
  src/android/events/InboxEvent.java
  src/android/events/NotificationOpenedEvent.java
  src/android/events/NotificationOptInEvent.java
  src/android/events/PushEvent.java
  src/android/events/RegistrationEvent.java
  www/UrbanAirship.js
Labels: mobile-review

#236 [MOBILE-215] Enable takeOff from JS for iOS
  plugin.xml
  src/ios/UACordovaPluginManager.h
  src/ios/UACordovaPluginManager.m
  src/ios/UAirshipPlugin.h
  src/ios/UAirshipPlugin.m
Labels: mobile-review
